setopt AUTO_CD              # Go to folder path without using cd.

setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

setopt CDABLE_VARS          # Change directory to a path stored in a variable.
setopt EXTENDED_GLOB        # Use extended globbing syntax.

setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

# Override colors
eval "$(dircolors -b $ZDOTDIR/dircolors)"

# aliases
source $DOTFILES/aliases/aliases

# prompt
fpath=($DOTFILES/zsh/prompt $fpath)
source $DOTFILES/zsh/prompt/default_setup

# completion
source $DOTFILES/zsh/completion.zsh

# autosuggestions
source "$DOTFILES/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"

# Binding
source "$DOTFILES/zsh/bindings.zsh"

export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"    # rust package manager
export PATH="$HOME/.krew/bin:$PATH"     # kubectl plugin manager

# fzf
if [ $(command -v "fzf") ]; then
    source $DOTFILES/zsh/fzf.zsh
fi

# direnv - autoload env files in project folder
if [ $(command -v "direnv") ]; then
    export DIRENV_CONFIG="$DOTFILES/direnv"
    eval "$(direnv hook zsh)"
fi

# pyenv
if [ $(command -v "pyenv") ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
fi
